version: '3'

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - /dockervolumes/authelia/config:/config
    ports:
      - 9091:9091
    restart: unless-stopped
    healthcheck:
      disable: true
    environment: 
      - TZ=Europe/Brussels
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - /dockervolumes/redis:/data
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=Europe/Brussels
