---
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - puid=1000
      - pgid=1000
      - app_url=http://wiki.bist-1.com
      - db_host=bookstack_db
      - db_user=bookstack
      - db_pass=ioihfseafdl
      - db_database=bookstackapp
    volumes:
      - /dockervolumes/bookstack:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=geertverbist
      - TZ=Europe/Brussels
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=ioihfseafdl

    volumes:
      - /dockervolumes/bookstackdb:/config
    restart: unless-stopped
